title: <p align="center"> Iwan La Udin </p> # your name (or website title) here
logo: "/images/photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/iwanlaudin/">LinkedIn</a> |
  <a href="https://github.com/iwanlaudin0101">GitHub</a>
  </p>
  
  <p align="justify">
  I am a Bachelor of Informatics Engineering at Khairun University in 2022.
  <br><br> 
  Highly interested in data field with a focus on data science, data analyst, and machine learning engineer.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
